### ISSUE TITLE
Wrong positioning in "Timeless" skin

### ISSUE THREAD

**Issue by tguiot** [prtksxna/persistent-toc#26]
pretty nice gadget !

small problem for my wiki : we're using the timeless skin, and the block for the floating TOC is a bit too high. the text "Contents" is partly hidden behind the wiki header.

I suppose I could load the ptoc.css content in my mediawiki:common.css and simply change the div position top to some value.

**Comment by tguiot** [comment]
fyi I did as I thought : I pasted the ptoc.css into my mediawiki:Common.css and changed
```
.floatTOC {
	...
	top: 0;
	...
```
to
```
.floatTOC {
	...
	top: 10pt;
	...
```
which made my floating TOC in the right position.

**Comment by prtksxna** [comment]
Hey @tguiot, thanks for trying out the gadget and reporting issues.
